### ISSUE TITLE
Need fix

### ISSUE THREAD

**Issue by billouetaudrey** [Ananasr/alldebrid#3]
Hello,

can you fix your app or any update ?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
./alldebrid: 35: [: =: unexpected operator
Bad link

Thanks :D

**Comment by billouetaudrey** [comment]
A friend make me Userbot module ;)

thanks
